name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-checks:
    name: Frontend Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Frontend structure check
        run: |
          echo "Checking frontend structure..."
          ls -la src/frontend/
          echo "Frontend check passed ✅"

  backend-checks:
    name: Backend Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Backend structure check
        run: |
          echo "Checking backend structure..."
          ls -la src/backend/
          echo "Backend check passed ✅"

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: [frontend-checks, backend-checks]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Integration check
        run: |
          echo "Running integration test..."
          echo "All components present:"
          ls -la src/
          echo "Integration test passed ✅"
